### ISSUE TITLE
Enabling the <script> tags.

### ISSUE THREAD

**Issue by crazywolf132** [LeaVerou/dabblet#256]
I would like to please enable the <script> tags, so i can run some tests please. How would i go about doing this?

**Comment by ankitchauhan186** [comment]
what are you saying.....

**Comment by LeaVerou** [comment]
I'm confused.

**Comment by ankitchauhan186** [comment]
what is confusing you mate.... contact me on my email ankitchauhan186@gmail.com

**Comment by LeaVerou** [comment]
Somebody here either has no clue how Github works or is spamming. Closing this.

**Comment by crazywolf132** [comment]
Wait, sorry i lost internet. Please contacted me at crazywolf132@gmail.com
