### ISSUE TITLE
Typo in CSS of 'Circular Text'

### ISSUE THREAD

**Issue by ruudlagcher** [LeaVerou/dabblet#261]
On line 18 of Circular Text ( http://play.csssecrets.io/circular-text ):
![circulartext-typo](https://cloud.githubusercontent.com/assets/18352663/14391020/0b91c22e-fdba-11e5-9021-fa49df87652c.png)

It should be without the leading 'x':
![circulartext-corr](https://cloud.githubusercontent.com/assets/18352663/14391084/48bb6c7c-fdba-11e5-8470-96fe0af0d135.png)

I love your book 'CSS Secrets'

**Comment by LeaVerou** [comment]
Fixed, thanks!
