### ISSUE TITLE
Import snipet into Silex with an API 

### ISSUE THREAD

**Issue by lexoyo** [LeaVerou/dabblet#262]
Hello

I am thinking of contributing a "import from dabblet" functionality to [Silex website builder](http://www.silex.me) (free & open source)

Given a snipt/gist URL, Is there an API or a simple way to get the HTML/CSS/JS code ?

Thx

**Comment by LeaVerou** [comment]
Yes, you just get the Github Gist!
https://developer.github.com/v3/gists/

**Comment by lexoyo** [comment]
Yes of course :)
Thank you
