### ISSUE TITLE
adding images from local memory

### ISSUE THREAD

**Issue by valzu1** [LeaVerou/dabblet#264]
How I can add images from my computer (local memory) when using CSS and HTML?

**Comment by LeaVerou** [comment]
You can upload them somewhere and use the URL. [Imgur](http://imgur.com/) is a popular choice.

**Comment by valzu1** [comment]
Thanks.

Lähettäjä: Lea Verou
Lähetetty: torstai 15. kesäkuuta 2017 00:35
Vastaanottaja: LeaVerou/dabblet
Kopio: valzu1; Author
Aihe: Re: [LeaVerou/dabblet] adding images from local memory (#264)

You can upload them somewhere and use the URL. Imgur is a popular choice.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



---
Avast Antivirus on tarkistanut tämän sähköpostin virusten varalta.
https://www.avast.com/antivirus
