### ISSUE TITLE
This request has been blocked;

### ISSUE THREAD

**Issue by zhuangyin8** [LeaVerou/dabblet#267]
Mixed Content: The page at 'https://dabblet.com/gist/f26dddc71730c3847153' was loaded over HTTPS, but requested an insecure script 'http://www.google-analytics.com/ga.js'. This request has been blocked; the content must be served over HTTPS.
f26dddc71730c3847153:125 Mixed Content: The page at 'https://dabblet.com/gist/f26dddc71730c3847153' was loaded over HTTPS, but requested an insecure resource 'http://preview.dabblet.com/'. This request has been blocked; the content must be served over HTTPS.

**Comment by LeaVerou** [comment]
This has been fixed a long time ago, closing.
