### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by sunlight200** [LeaVerou/dabblet#273]
I can not log into my dabblet ,the pop up screen gives me white page as in this screenshot http://prntscr.com/jyxskr

**Comment by LeaVerou** [comment]
Can't reproduce over here, it seems to work fine. Did it work before? Perhaps an extension or something is blocking it?

**Comment by LeaVerou** [comment]
Also, which browser are you using?

**Comment by sunlight200** [comment]
I use google chrome ,I cleaned it's cache and after I did ,I could log in to github but I could not log in to dabblet 
and yes it was working before ,I was using dabblet till 2 days ago and I just faced this issue yesterday

**Comment by LeaVerou** [comment]
Do you get the white page immediately or after you log in? What happens if you try it in a different browser?

**Comment by sunlight200** [comment]
Every time I click on log in icon ,a page pop up and asks me to sign into my github account ,I write my info then click to sign in , the page loads as it would redirect me to my account then it stops and it turns to white ,I just tried firefox and I got the same issue ,look at this screenshot ,its from firefox http://prntscr.com/jzrtfm

**Comment by LeaVerou** [comment]
Could you be behind a very restrictive firewall or something? Have you tried from a different connection?

**Comment by Potherca** [comment]
I have the same issue in Chrome. When I look in the inspector of the `oauth.php` window, I see the following error:

![screenshot at 2018-09-07 13-03-23](https://user-images.githubusercontent.com/195757/45215658-6bebea00-b29e-11e8-8dc7-c5fcbc89e116.png)


> Uncaught DOMException: Blocked a frame with origin "http://dabblet.com" from accessing a cross-origin frame.

Could this be a HTTPS issue? Otherwise it looks like something is wrong with the CORRS headers...

**Comment by Potherca** [comment]
Yup... it looks to be related to HTTP vs. HTTPS. When I am on HTTP everything works fine. On HTTPS it all breaks...

**Comment by abdelrahmanmann** [comment]
The issue is still. Anyone has the solution?

**Comment by abdelrahmanmann** [comment]
I can't login with GitHub or save the code as gist

**Comment by LeaVerou** [comment]
Confirmed.

**Comment by abdelrahmanmann** [comment]
Now dabblet lost its most important function which is connecting to GitHub. It has bugs with oauth

**Comment by LeaVerou** [comment]
@abdelrahmanmann I understand your frustration, but posting more comments here will not help me fix it any faster. Either help by debugging, or sit back and wait until the issue is fixed. Thank you.

**Comment by abdelrahmanmann** [comment]
Thank you I wanted to confirm that you know the bug. And thanks for your reply and attention.
