### ISSUE TITLE
404 Error - Link to: View Full Page Result

### ISSUE THREAD

**Issue by NWTC-Web-i-robert** [LeaVerou/dabblet#276]
Hi Lea - 

Following the examples from CSS Secrets on the dabblet site the link to: View full page result is returning a 404 error on your main site.

Cheers,

Robert Buchholz

![Screen Shot 2020-10-08 at 4 14 20 PM](https://user-images.githubusercontent.com/30782996/95514673-f0c7f700-0981-11eb-9041-6ade8fbe4858.png)

![Screen Shot 2020-10-08 at 4 19 55 PM](https://user-images.githubusercontent.com/30782996/95514786-2371ef80-0982-11eb-9f78-5206de23ebae.png)

**Comment by LeaVerou** [comment]
Thank you for the report! I can confirm this. Investigating.

**Comment by LeaVerou** [comment]
This seems to work now, closing. Feel free to reopen if it happens again!
